### ISSUE TITLE
docs(formation): confirm the build process for templates and code

### ISSUE THREAD

**Issue by mikerkeating** [mahabis/formation#10]

**Comment by shanereid** [comment]
Ideal folder structure:
- `index.html`
- `assets/templates/forms.json`
- `assets/templates/bootstrap/*.html`
- `template.py`

That structure is all relative to the index.html, so the template.py would be on the same level as it. You can move it up a level (what I do), however you'll have to change the path set to the `template_folder` variable in the `template.py` file to point to the right place.

Once that's fine, simply put your templates in the `assets/templates/bootstrap` folder, create your forms in `forms.json` and in terminal compile everything into `templates.json` by using `cd` to get to the folder with the `template.py` and running `python template.py`

@mikerkeating

**Comment by mikerkeating** [comment]
- [x] all sorted now - build files changed and templates are built
