### ISSUE TITLE
docs(formation): how to show confirmation screen

### ISSUE THREAD

**Issue by mikerkeating** [mahabis/formation#11]

**Comment by shanereid** [comment]
@mikerkeating 

Confirmation Screen?
Need a bit more info for this - not sure what you mean or what elements are inside the confirmation screen

**Comment by mikerkeating** [comment]
@shanereid 

- see the url and access details in https://github.com/mahabis/mahabis-ui/issues/2
- want to show a `you have submitted view` and not the form with confirmation message below - more obvious that form sent

**Comment by mikerkeating** [comment]
@shanereid 

- this could be a simple as how to specify transition from `form template` to `confirmation template` on receipt of success

**Comment by shanereid** [comment]
@mikerkeating 

For this one, you could do something like this:
Javascript:
```
(function() {
    // Grab the form reference
    var $form = $('.container .test-form');

    // When you submit the form
    $form.on('submit', function() {
        var $category = $form.find('[name=category]');

        $.get('/submit-endpoint', {
            'category':category.val()
        }, function(response) { // This is callback, We're assuming response is {"life-options":["One Option","Another Option"]}
            $form.replaceWith(formation.template('confirmation-template-yo', {
                'some-template-variable':'some-template-value'
            }));
        });
    });
})();
```
