### ISSUE TITLE
docs(formation): how to pass in values at start + querystring

### ISSUE THREAD

**Issue by mikerkeating** [mahabis/formation#7]
Context

1. Form will be triggered by user clicking on a link. We want to pass data into the form via the link
1. Page & Form can be triggered bt user clicking on a link (with querystring params) in an email and opening the page. We want to pass data into the form. 

Docs

- How to do this?
- re querystrings - should this be done by the form or the page?

**Comment by shanereid** [comment]
@mikerkeating 

- Query Strings don't need any special setup - any query string values that match the name of a field in the form will populate the field. Typing this out I realise this is probably quite bad, so next piece of work I do I'll slip in prefix, so you can prefix the qs keys so you don't get interference.
- If you want to pass data in with code, use the second argument of `.form`, in the format:
```
{
   "field_name":"field_value"
}
```
