### ISSUE TITLE
docs(formation): background data/ hidden fields

### ISSUE THREAD

**Issue by mikerkeating** [mahabis/formation#8]
Context

- Want to pass data into API request when form is submitted - IP address; referrer; browser
- Data passed into the form at start-up should be hidden from the user

Docs

- How to handle this? Can the data be defined as fields and hidden?

**Comment by shanereid** [comment]
@mikerkeating 

Yes, you can use the `hidden` form type, so something like this in your `forms.json`:

```
"forms": {
    "example": [
        {
            "type":"hidden",
            "name":"user_agent"
        }
    ]
}
```

and then this in the code:

```
formation.form('example', {'user_agent':{'value':navigator.userAgent}});
```
