### ISSUE TITLE
docs(formation): how to persist data between forms

### ISSUE THREAD

**Issue by mikerkeating** [mahabis/formation#9]
Context

- User will submit form 1 and then be presented with and submit form 2
- We need data from 1 (email, order id) to be persisted and submitted with form 2

Docs

- How to do this within formation?

**Comment by shanereid** [comment]
@mikerkeating 

If the field names in the two forms are persistent, you can use `.extract($form)` on the first, completed form and you can use the return value as the `values` parameter of the `.form` if when you create the second form. So, something alone the lines of:

```
var $form1 = $('#form1'),
    values = formation.extract($form1),
    $form2 = formation.form('form-2-template', values);
$form1.replaceWith($form2);
```

**Comment by shanereid** [comment]
@mikerkeating before this will work I may need to make a patch, but I'll make it tonight
